runtime: python
env: flex

runtime_config:
    python_version: 3

api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: wsgi.app

libraries:
  - name: ssl
    version: latest

skip_files: venv


